import { Student, Room, Agreement, PaymentRecord, ActivityLog, OwnerProfile } from './types';

export const initialStudents: Student[] = [
  {
    id: 'stud-1',
    studentNumber: '222082927',
    idNumber: '031110 5234 081',
    fullName: 'Ramadulwane Daniel Mohlomi',
    shortName: 'RD Mohlomi',
    initials: 'RM',
    email: 'mramadulwane@gmail.com',
    phone: '+27 67 240 2175',
    institution: 'Central University Of Technology',
    course: 'Diploma in Information Technology',
    assignedRoomId: 'room-01',
    agreementStatus: 'Active',
    emergencyContact: {
      name: 'Ramadulwane Mohlomi Sr.',
      phone: '+27 82 555 9012',
    },
    avatarColor: 'bg-emerald-600',
    agreementId: 'SA001',
    account: {
      username: 'rmohlomi26',
      temporaryPassword: 'ResiPass2026!',
      accountCreatedDate: '15 Jan 2026',
      accountStatus: 'Active',
      mustChangePassword: false,
    },
  },
  {
    id: 'stud-2',
    studentNumber: '222059872',
    idNumber: '031110 6149 089',
    fullName: 'Lebohang Matlhoane',
    shortName: 'L Matlhoane',
    initials: 'LM',
    email: 'lmatlhoane@gmail.com',
    phone: '+27 67 240 8891',
    institution: 'Central University Of Technology',
    course: 'Diploma in Information Technology',
    assignedRoomId: 'room-02',
    agreementStatus: 'Pending Verification',
    emergencyContact: {
      name: 'Matlhoane Family',
      phone: '+27 82 555 9012',
    },
    avatarColor: 'bg-blue-600',
    agreementId: 'SA002',
    account: {
      username: 'lmatlhoane26',
      temporaryPassword: 'ResiPass2026!',
      accountCreatedDate: '20 Jan 2026',
      accountStatus: 'Pending First Login',
      mustChangePassword: true,
    },
  },
  {
    id: 'stud-3',
    studentNumber: '222093279',
    idNumber: '031110 7412 083',
    fullName: 'Letlotlo P Moloi',
    shortName: 'LP Moloi',
    initials: 'LM',
    email: 'yadayadamoloi98@gmail.com',
    phone: '+27 63 465 6632',
    institution: 'Central University Of Technology',
    course: 'Diploma in Information Technology',
    assignedRoomId: 'room-03',
    agreementStatus: 'Active',
    emergencyContact: {
      name: 'Moloi Guardian',
      phone: '+27 82 555 9012',
    },
    avatarColor: 'bg-indigo-600',
    agreementId: 'SA003',
    account: {
      username: 'lpmoloi26',
      temporaryPassword: 'ResiPass2026!',
      accountCreatedDate: '22 Jan 2026',
      accountStatus: 'Active',
      mustChangePassword: false,
    },
  },
];

export const initialRooms: Room[] = [
  {
    id: 'room-01',
    roomNumber: 'Room 01',
    block: 'Block A',
    floor: '1st Floor',
    roomType: 'Single Suite',
    capacity: 1,
    bedsCount: '1 Single Bed (Single Occupancy)',
    monthlyRent: 2500,
    status: 'Occupied',
    assignedStudentIds: ['stud-1'],
    amenities: [
      'Single Bed',
      'Study Desk',
      'Built-in Wardrobe',
      'High-Speed Wi-Fi',
      'En-suite Bathroom',
      'Heating',
      'Common Kitchen',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    description: 'Quiet single room facing the campus gardens with private en-suite bathroom and dedicated workstation.',
  },
  {
    id: 'room-02',
    roomNumber: 'Room 02',
    block: 'Block B',
    floor: 'Ground Floor',
    roomType: 'Double Unit',
    capacity: 2,
    bedsCount: '2 Beds (Sharing Room)',
    monthlyRent: 3500,
    status: '1 Bed Occupied',
    assignedStudentIds: ['stud-2'],
    amenities: [
      '2 Beds , Sharing Room',
      'Study Desk',
      'Built-in Wardrobe',
      'High-Speed Wi-Fi',
      'Common Kitchen',
      'Security',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80',
    description: 'Spacious ground floor sharing unit with easy access to laundry and common entertainment hall.',
  },
  {
    id: 'room-03',
    roomNumber: 'Room 03',
    block: 'Block A',
    floor: '2nd Floor',
    roomType: 'Single Suite',
    capacity: 1,
    bedsCount: '1 Single Bed (Single Occupancy)',
    monthlyRent: 2800,
    status: 'Occupied',
    assignedStudentIds: ['stud-3'],
    amenities: [
      'Single Bed',
      'Study Desk',
      'Built-in Wardrobe',
      'High-Speed Wi-Fi',
      'En-suite Bathroom',
      'Heating',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80',
    description: 'Bright top-floor single room with scenic view, premium fiber internet, and full heating for winter.',
  },
  {
    id: 'room-04',
    roomNumber: 'Room 04',
    block: 'Block B',
    floor: '1st Floor',
    roomType: 'Single Suite',
    capacity: 1,
    bedsCount: '1 Single Bed (Single Occupancy)',
    monthlyRent: 3000,
    status: 'Available',
    assignedStudentIds: [],
    amenities: [
      'Single Bed',
      'Study Desk',
      'Built-in Wardrobe',
      'High-Speed Wi-Fi',
      'En-suite Bathroom',
      'Common Kitchen',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    description: 'Newly renovated vacant single suite ready for immediate 2026 student resident placement.',
  },
];

export const initialAgreements: Agreement[] = [
  {
    id: 'SA001',
    studentId: 'stud-1',
    roomId: 'room-01',
    leaseTerm: '12 Months (Full Academic Year)',
    startDate: '01 February 2026',
    endDate: '30 November 2026',
    monthlyRental: 2500,
    securityDeposit: 2500,
    securityDepositStatus: 'Paid',
    status: 'Active',
    signedByStudent: true,
    signedDate: '28 Jan 2026',
    clauses: {
      purpose: 'The Premises shall be used solely as student accommodation. Any unauthorized commercial exploitation is strictly prohibited.',
      rentalPeriod: 'The lease runs for a fixed period of 12 months, commencing on the defined Start Date, subject to compliance.',
      paymentTerms: 'Monthly rent must be paid in full by the 1st of every calendar month. Late payments incur automated penalty percentages.',
      useOfPremises: 'Quiet hours are enforced after 10:00 PM. No unauthorized structural or technical modifications are permitted on site.',
    },
  },
  {
    id: 'SA002',
    studentId: 'stud-2',
    roomId: 'room-02',
    leaseTerm: '12 Months (Full Academic Year)',
    startDate: '01 February 2026',
    endDate: '30 November 2026',
    monthlyRental: 3500,
    securityDeposit: 3500,
    securityDepositStatus: 'Paid',
    status: 'Active',
    signedByStudent: true,
    signedDate: '30 Jan 2026',
    clauses: {
      purpose: 'The Premises shall be used solely as student accommodation. Any unauthorized commercial exploitation is strictly prohibited.',
      rentalPeriod: 'The lease runs for a fixed period of 12 months, commencing on the defined Start Date, subject to compliance.',
      paymentTerms: 'Monthly rent must be paid in full by the 1st of every calendar month. Late payments incur automated penalty percentages.',
      useOfPremises: 'Quiet hours are enforced after 10:00 PM. No unauthorized structural or technical modifications are permitted on site.',
    },
  },
  {
    id: 'SA003',
    studentId: 'stud-3',
    roomId: 'room-03',
    leaseTerm: '12 Months (Full Academic Year)',
    startDate: '01 February 2026',
    endDate: '30 November 2026',
    monthlyRental: 2800,
    securityDeposit: 2800,
    securityDepositStatus: 'Paid',
    status: 'Active',
    signedByStudent: true,
    signedDate: '01 Feb 2026',
    clauses: {
      purpose: 'The Premises shall be used solely as student accommodation. Any unauthorized commercial exploitation is strictly prohibited.',
      rentalPeriod: 'The lease runs for a fixed period of 12 months, commencing on the defined Start Date, subject to compliance.',
      paymentTerms: 'Monthly rent must be paid in full by the 1st of every calendar month. Late payments incur automated penalty percentages.',
      useOfPremises: 'Quiet hours are enforced after 10:00 PM. No unauthorized structural or technical modifications are permitted on site.',
    },
  },
];

export const initialPayments: PaymentRecord[] = [
  // Mohlomi payments (Room 01)
  {
    id: 'pay-01',
    studentId: 'stud-1',
    roomId: 'room-01',
    transactionPeriod: 'February 2026',
    amount: 2500,
    paymentDate: '02 Feb 2026',
    dueDate: '01 Feb 2026',
    status: 'Paid',
    reference: 'INV-0125-01',
    paymentMethod: 'Capitec Bank EFT',
  },
  {
    id: 'pay-02',
    studentId: 'stud-1',
    roomId: 'room-01',
    transactionPeriod: 'March 2026',
    amount: 2500,
    paymentDate: '01 Mar 2026',
    dueDate: '01 Mar 2026',
    status: 'Paid',
    reference: 'PAY0Transfer',
    paymentMethod: 'Capitec Bank EFT',
  },
  {
    id: 'pay-03',
    studentId: 'stud-1',
    roomId: 'room-01',
    transactionPeriod: 'April 2026',
    amount: 2500,
    paymentDate: null,
    dueDate: '01 Apr 2026',
    status: 'Pending',
    reference: 'SA001',
    paymentMethod: 'Capitec Bank EFT',
  },
  {
    id: 'pay-04',
    studentId: 'stud-1',
    roomId: 'room-01',
    transactionPeriod: 'May 2026',
    amount: 2500,
    paymentDate: null,
    dueDate: '01 May 2026',
    status: 'Pending',
    reference: 'SA001',
    paymentMethod: 'Capitec Bank EFT',
  },

  // Matlhoane payments (Room 02)
  {
    id: 'pay-05',
    studentId: 'stud-2',
    roomId: 'room-02',
    transactionPeriod: 'February 2026',
    amount: 3500,
    paymentDate: '05 Feb 2026',
    dueDate: '01 Feb 2026',
    status: 'Paid',
    reference: 'INV-0225-02',
    paymentMethod: 'Capitec Bank EFT',
  },
  {
    id: 'pay-06',
    studentId: 'stud-2',
    roomId: 'room-02',
    transactionPeriod: 'March 2026',
    amount: 3500,
    paymentDate: '01 Mar 2026',
    dueDate: '01 Mar 2026',
    status: 'Paid',
    reference: 'PAY0Transfer',
    paymentMethod: 'EFT / Bank Transfer',
  },
  {
    id: 'pay-07',
    studentId: 'stud-2',
    roomId: 'room-02',
    transactionPeriod: 'April 2026',
    amount: 3500,
    paymentDate: null,
    dueDate: '08 Oct 2026',
    status: 'Pending',
    reference: 'INV-0425-02',
    paymentMethod: 'EFT / Bank Transfer',
  },

  // Moloi payments (Room 03)
  {
    id: 'pay-08',
    studentId: 'stud-3',
    roomId: 'room-03',
    transactionPeriod: 'February 2026',
    amount: 2800,
    paymentDate: '01 Feb 2026',
    dueDate: '01 Feb 2026',
    status: 'Paid',
    reference: 'PAY0Transfer',
    paymentMethod: 'EFT / Bank Transfer',
  },
  {
    id: 'pay-09',
    studentId: 'stud-3',
    roomId: 'room-03',
    transactionPeriod: 'March 2026',
    amount: 2800,
    paymentDate: '04 Mar 2026',
    dueDate: '01 Mar 2026',
    status: 'Paid',
    reference: 'INV-0325-01',
    paymentMethod: 'Capitec Bank EFT',
  },
  {
    id: 'pay-10',
    studentId: 'stud-3',
    roomId: 'room-03',
    transactionPeriod: 'April 2026',
    amount: 2800,
    paymentDate: null,
    dueDate: '01 Sep 2026',
    status: 'Pending',
    reference: 'EFT-994821034-MOLOI',
    paymentMethod: 'EFT / Bank Transfer',
  },
];

export const initialActivities: ActivityLog[] = [
  {
    id: 'act-1',
    title: 'Payment received',
    subtitle: 'R2,500.00 • Today (Room 01 - RD Mohlomi)',
    timeAgo: 'Just now',
    type: 'payment',
  },
  {
    id: 'act-2',
    title: 'New student registration completed',
    subtitle: 'RD Mohlomi assigned to Room 01 (Block A)',
    timeAgo: '1 hour ago',
    type: 'registration',
  },
  {
    id: 'act-3',
    title: 'New student registration completed',
    subtitle: 'L Matlhoane assigned to Room 02 (Block B)',
    timeAgo: '1 hour ago',
    type: 'registration',
  },
  {
    id: 'act-4',
    title: 'New student registration completed',
    subtitle: 'LP Moloi assigned to Room 03 (Block A)',
    timeAgo: '1 hour ago',
    type: 'registration',
  },
  {
    id: 'act-5',
    title: 'Agreement updated & verified',
    subtitle: 'Block A - Room 01 • Lease renewed',
    timeAgo: 'Yesterday',
    type: 'agreement',
  },
  {
    id: 'act-6',
    title: 'Monthly rental payment received',
    subtitle: 'R3,500 received for Room 02 (L Matlhoane)',
    timeAgo: '2 days ago',
    type: 'payment',
  },
  {
    id: 'act-7',
    title: 'Maintenance completed',
    subtitle: 'Fridge repaired in Block B Common Kitchen',
    timeAgo: '2 days ago',
    type: 'maintenance',
  },
  {
    id: 'act-8',
    title: 'Maintenance completed',
    subtitle: 'Geyser repaired • Block A hot water restored',
    timeAgo: '3 days ago',
    type: 'maintenance',
  },
];

export const initialOwnerProfile: OwnerProfile = {
  name: 'Ms PC Makhele',
  title: 'Property Owner',
  email: 'makhelepulane1@gmail.com',
  phone: '+27 82 123 4567',
  alternativePhone: 'Not set',
  bankName: 'Capitec Bank',
  accountNumber: '123456789',
  accountType: 'Cheque',
  paymentReference: 'SA001',
  notifications: {
    newBookings: true,
    rentPayments: true,
    maintenanceAlerts: true,
  },
};

export const monthlyRevenueStats = [
  { month: 'Sep', amount: 5000, label: 'R5k' },
  { month: 'Oct', amount: 6500, label: 'R6.5k' },
  { month: 'Nov', amount: 7000, label: 'R7k' },
  { month: 'Dec', amount: 8000, label: 'R8k' },
  { month: 'Jan', amount: 10000, label: 'R10k' },
];
