import {
  Student,
  Room,
  Agreement,
  PaymentRecord,
  ActivityLog,
  OwnerProfile,
  MaintenanceRequest,
} from './types';

export const initialStudents: Student[] = [
  {
    id: 'stud-1',
    studentNumber: '222082927',
    idNumber: '031110 5234 081',
    fullName: 'Ramadulwane Daniel Mohlomi',
    shortName: 'RD Mohlomi',
    initials: 'RM',
    email: 'mramadulwane@gmail.com',
    phone: '+27 67 240 2175',
    institution: 'Central University Of Technology',
    course: 'Diploma in Information Technology',
    assignedRoomId: 'room-01',
    agreementStatus: 'Active',
    emergencyContact: {
      name: 'Ramadulwane Mohlomi Sr.',
      phone: '+27 82 555 9012',
    },
    avatarColor: 'bg-emerald-600',
    agreementId: 'SA001',
    password: 'ResiPass2026!',
    emailConfirmed: true,
    account: {
      username: 'rmohlomi26',
      password: 'ResiPass2026!',
      temporaryPassword: 'ResiPass2026!',
      accountCreatedDate: '15 Jan 2026',
      accountStatus: 'Active',
      isEmailVerified: true,
      mustChangePassword: false,
    },
  },
  {
    id: 'stud-2',
    studentNumber: '222059872',
    idNumber: '031110 6149 089',
    fullName: 'Lebohang Matlhoane',
    shortName: 'L Matlhoane',
    initials: 'LM',
    email: 'lmatlhoane@gmail.com',
    password: 'ResiPass2026!',
    emailConfirmed: true,
    phone: '+27 67 240 8891',
    institution: 'Central University Of Technology',
    course: 'Diploma in Information Technology',
    assignedRoomId: 'room-02',
    agreementStatus: 'Pending Verification',
    emergencyContact: {
      name: 'Matlhoane Family',
      phone: '+27 82 555 9012',
    },
    avatarColor: 'bg-blue-600',
    agreementId: 'SA002',
    account: {
      username: 'lmatlhoane26',
      password: 'ResiPass2026!',
      temporaryPassword: 'ResiPass2026!',
      accountCreatedDate: '20 Jan 2026',
      accountStatus: 'Active',
      isEmailVerified: true,
      mustChangePassword: true,
    },
  },
  {
    id: 'stud-3',
    studentNumber: '222093279',
    idNumber: '031110 7412 083',
    fullName: 'Letlotlo P Moloi',
    shortName: 'LP Moloi',
    initials: 'LM',
    email: 'yadayadamoloi98@gmail.com',
    password: 'ResiPass2026!',
    emailConfirmed: true,
    phone: '+27 63 465 6632',
    institution: 'Central University Of Technology',
    course: 'Diploma in Information Technology',
    assignedRoomId: 'room-03',
    agreementStatus: 'Active',
    emergencyContact: {
      name: 'Moloi Guardian',
      phone: '+27 82 555 9012',
    },
    avatarColor: 'bg-indigo-600',
    agreementId: 'SA003',
    account: {
      username: 'lpmoloi26',
      password: 'ResiPass2026!',
      temporaryPassword: 'ResiPass2026!',
      accountCreatedDate: '22 Jan 2026',
      accountStatus: 'Active',
      isEmailVerified: true,
      mustChangePassword: false,
    },
  },
];

export const initialRooms: Room[] = [
  {
    id: 'room-01',
    roomNumber: 'Room 01',
    block: 'Block A',
    floor: '1st Floor',
    roomType: 'Single Suite',
    capacity: 1,
    bedsCount: '1 Single Bed (Single Occupancy)',
    monthlyRent: 2500,
    status: 'Occupied',
    assignedStudentIds: ['stud-1'],
    amenities: [
      'Single Bed',
      'Study Desk',
      'Built-in Wardrobe',
      'High-Speed Wi-Fi',
      'En-suite Bathroom',
      'Heating',
      'Common Kitchen',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    description: 'Quiet single room facing the campus gardens with private en-suite bathroom and dedicated workstation.',
  },
  {
    id: 'room-02',
    roomNumber: 'Room 02',
    block: 'Block B',
    floor: 'Ground Floor',
    roomType: 'Double Unit',
    capacity: 2,
    bedsCount: '2 Beds (Sharing Room)',
    monthlyRent: 3500,
    status: '1 Bed Occupied',
    assignedStudentIds: ['stud-2'],
    amenities: [
      '2 Beds , Sharing Room',
      'Study Desk',
      'Built-in Wardrobe',
      'High-Speed Wi-Fi',
      'Common Kitchen',
      'Security',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80',
    description: 'Spacious ground floor sharing unit with easy access to laundry and common entertainment hall.',
  },
  {
    id: 'room-03',
    roomNumber: 'Room 03',
    block: 'Block A',
    floor: '2nd Floor',
    roomType: 'Single Suite',
    capacity: 1,
    bedsCount: '1 Single Bed (Single Occupancy)',
    monthlyRent: 2800,
    status: 'Occupied',
    assignedStudentIds: ['stud-3'],
    amenities: [
      'Single Bed',
      'Study Desk',
      'Built-in Wardrobe',
      'High-Speed Wi-Fi',
      'En-suite Bathroom',
      'Heating',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80',
    description: 'Bright top-floor single room with scenic view, premium fiber internet, and full heating for winter.',
  },
  {
    id: 'room-04',
    roomNumber: 'Room 04',
    block: 'Block B',
    floor: '1st Floor',
    roomType: 'Single Suite',
    capacity: 1,
    bedsCount: '1 Single Bed (Single Occupancy)',
    monthlyRent: 3000,
    status: 'Available',
    assignedStudentIds: [],
    amenities: [
      'Single Bed',
      'Study Desk',
      'Built-in Wardrobe',
      'High-Speed Wi-Fi',
      'En-suite Bathroom',
      'Common Kitchen',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    description: 'Newly renovated vacant single suite ready for immediate 2026 student resident placement.',
  },
];

export const initialAgreements: Agreement[] = [
  {
    id: 'SA001',
    studentId: 'stud-1',
    roomId: 'room-01',
    leaseTerm: '12 Months (Full Academic Year)',
    startDate: '01 February 2026',
    endDate: '30 November 2026',
    monthlyRental: 2500,
    securityDeposit: 2500,
    securityDepositStatus: 'Paid',
    status: 'Active',
    signedByStudent: true,
    signedDate: '28 Jan 2026',
    clauses: {
      purpose: 'The Premises shall be used solely as student accommodation. Any unauthorized commercial exploitation is strictly prohibited.',
      rentalPeriod: 'The lease runs for a fixed period of 12 months, commencing on the defined Start Date, subject to compliance.',
      paymentTerms: 'Monthly rent must be paid in full by the 1st of every calendar month. Late payments incur automated penalty percentages.',
      useOfPremises: 'Quiet hours are enforced after 10:00 PM. No unauthorized structural or technical modifications are permitted on site.',
    },
  },
  {
    id: 'SA002',
    studentId: 'stud-2',
    roomId: 'room-02',
    leaseTerm: '12 Months (Full Academic Year)',
    startDate: '01 February 2026',
    endDate: '30 November 2026',
    monthlyRental: 3500,
    securityDeposit: 3500,
    securityDepositStatus: 'Paid',
    status: 'Active',
    signedByStudent: true,
    signedDate: '30 Jan 2026',
    clauses: {
      purpose: 'The Premises shall be used solely as student accommodation. Any unauthorized commercial exploitation is strictly prohibited.',
      rentalPeriod: 'The lease runs for a fixed period of 12 months, commencing on the defined Start Date, subject to compliance.',
      paymentTerms: 'Monthly rent must be paid in full by the 1st of every calendar month. Late payments incur automated penalty percentages.',
      useOfPremises: 'Quiet hours are enforced after 10:00 PM. No unauthorized structural or technical modifications are permitted on site.',
    },
  },
  {
    id: 'SA003',
    studentId: 'stud-3',
    roomId: 'room-03',
    leaseTerm: '12 Months (Full Academic Year)',
    startDate: '01 February 2026',
    endDate: '30 November 2026',
    monthlyRental: 2800,
    securityDeposit: 2800,
    securityDepositStatus: 'Paid',
    status: 'Active',
    signedByStudent: true,
    signedDate: '01 Feb 2026',
    clauses: {
      purpose: 'The Premises shall be used solely as student accommodation. Any unauthorized commercial exploitation is strictly prohibited.',
      rentalPeriod: 'The lease runs for a fixed period of 12 months, commencing on the defined Start Date, subject to compliance.',
      paymentTerms: 'Monthly rent must be paid in full by the 1st of every calendar month. Late payments incur automated penalty percentages.',
      useOfPremises: 'Quiet hours are enforced after 10:00 PM. No unauthorized structural or technical modifications are permitted on site.',
    },
  },
];

export const initialPayments: PaymentRecord[] = [
  // Mohlomi payments (Room 01)
  {
    id: 'pay-01',
    studentId: 'stud-1',
    roomId: 'room-01',
    transactionPeriod: 'February 2026',
    amount: 2500,
    paymentDate: '02 Feb 2026',
    dueDate: '01 Feb 2026',
    status: 'Paid',
    reference: 'INV-0125-01',
    paymentMethod: 'Capitec Bank EFT',
  },
  {
    id: 'pay-02',
    studentId: 'stud-1',
    roomId: 'room-01',
    transactionPeriod: 'March 2026',
    amount: 2500,
    paymentDate: '01 Mar 2026',
    dueDate: '01 Mar 2026',
    status: 'Paid',
    reference: 'PAY0Transfer',
    paymentMethod: 'Capitec Bank EFT',
  },
  {
    id: 'pay-03',
    studentId: 'stud-1',
    roomId: 'room-01',
    transactionPeriod: 'April 2026',
    amount: 2500,
    paymentDate: null,
    dueDate: '01 Apr 2026',
    status: 'Pending',
    reference: 'SA001',
    paymentMethod: 'Capitec Bank EFT',
  },
  {
    id: 'pay-04',
    studentId: 'stud-1',
    roomId: 'room-01',
    transactionPeriod: 'May 2026',
    amount: 2500,
    paymentDate: null,
    dueDate: '01 May 2026',
    status: 'Pending',
    reference: 'SA001',
    paymentMethod: 'Capitec Bank EFT',
  },

  // Matlhoane payments (Room 02)
  {
    id: 'pay-05',
    studentId: 'stud-2',
    roomId: 'room-02',
    transactionPeriod: 'February 2026',
    amount: 3500,
    paymentDate: '05 Feb 2026',
    dueDate: '01 Feb 2026',
    status: 'Paid',
    reference: 'INV-0225-02',
    paymentMethod: 'Capitec Bank EFT',
  },
  {
    id: 'pay-06',
    studentId: 'stud-2',
    roomId: 'room-02',
    transactionPeriod: 'March 2026',
    amount: 3500,
    paymentDate: '01 Mar 2026',
    dueDate: '01 Mar 2026',
    status: 'Paid',
    reference: 'PAY0Transfer',
    paymentMethod: 'EFT / Bank Transfer',
  },
  {
    id: 'pay-07',
    studentId: 'stud-2',
    roomId: 'room-02',
    transactionPeriod: 'April 2026',
    amount: 3500,
    paymentDate: null,
    dueDate: '08 Oct 2026',
    status: 'Pending',
    reference: 'INV-0425-02',
    paymentMethod: 'EFT / Bank Transfer',
  },

  // Moloi payments (Room 03)
  {
    id: 'pay-08',
    studentId: 'stud-3',
    roomId: 'room-03',
    transactionPeriod: 'February 2026',
    amount: 2800,
    paymentDate: '01 Feb 2026',
    dueDate: '01 Feb 2026',
    status: 'Paid',
    reference: 'PAY0Transfer',
    paymentMethod: 'EFT / Bank Transfer',
  },
  {
    id: 'pay-09',
    studentId: 'stud-3',
    roomId: 'room-03',
    transactionPeriod: 'March 2026',
    amount: 2800,
    paymentDate: '04 Mar 2026',
    dueDate: '01 Mar 2026',
    status: 'Paid',
    reference: 'INV-0325-01',
    paymentMethod: 'Capitec Bank EFT',
  },
  {
    id: 'pay-10',
    studentId: 'stud-3',
    roomId: 'room-03',
    transactionPeriod: 'April 2026',
    amount: 2800,
    paymentDate: null,
    dueDate: '01 Sep 2026',
    status: 'Pending',
    reference: 'EFT-994821034-MOLOI',
    paymentMethod: 'EFT / Bank Transfer',
  },
];

export const initialActivities: ActivityLog[] = [
  {
    id: 'act-1',
    title: 'Rent payment received',
    subtitle: 'R2,500.00 received for February 2026 from RD Mohlomi (Room 01 - Block A) via Instant EFT. Ledger updated.',
    timeAgo: 'Just now',
    timestamp: '24 Feb 2026, 12:45',
    type: 'payment',
    status: 'Paid',
    previousStatus: 'Pending',
    entityId: 'pay-01',
    entityType: 'payment',
    amount: 2500,
    studentName: 'Ramadulwane Daniel Mohlomi',
    roomNumber: 'Room 01',
    actor: 'Student (RD Mohlomi)',
  },
  {
    id: 'act-2',
    title: 'Maintenance status changed to In Progress',
    subtitle: 'Leaking shower mixer valve (Room 02 - Block B) moved to In Progress. FastPlumb Services on site.',
    timeAgo: '15 mins ago',
    timestamp: '24 Feb 2026, 12:30',
    type: 'maintenance',
    status: 'In Progress',
    previousStatus: 'Scheduled',
    entityId: 'MR-102',
    entityType: 'maintenance',
    studentName: 'Lebohang Matlhoane',
    roomNumber: 'Room 02',
    priority: 'High',
    actor: 'Owner (Ms PC Makhele)',
  },
  {
    id: 'act-3',
    title: 'New maintenance request reported',
    subtitle: 'Deadbolt lock cylinder sticking • Room 03 (Block A) reported by LP Moloi. Priority: High.',
    timeAgo: '40 mins ago',
    timestamp: '24 Feb 2026, 12:05',
    type: 'maintenance',
    status: 'Reported',
    entityId: 'MR-103',
    entityType: 'maintenance',
    studentName: 'Letlotlo P Moloi',
    roomNumber: 'Room 03',
    priority: 'High',
    actor: 'Resident (LP Moloi)',
  },
  {
    id: 'act-4',
    title: 'Maintenance task scheduled',
    subtitle: 'Flickering desk lamp socket (Room 01) scheduled for Wed 10:00 AM with Electrician David Ndlovu.',
    timeAgo: '2 hours ago',
    timestamp: '24 Feb 2026, 10:30',
    type: 'maintenance',
    status: 'Scheduled',
    previousStatus: 'Reported',
    entityId: 'MR-101',
    entityType: 'maintenance',
    studentName: 'Ramadulwane Daniel Mohlomi',
    roomNumber: 'Room 01',
    priority: 'Medium',
    actor: 'Owner (Ms PC Makhele)',
  },
  {
    id: 'act-5',
    title: 'Rent payment received',
    subtitle: 'R3,500.00 received for January 2026 from Lebohang Matlhoane (Room 02 - Block B) via Capitec Pay.',
    timeAgo: 'Yesterday',
    timestamp: '23 Feb 2026, 16:15',
    type: 'payment',
    status: 'Paid',
    previousStatus: 'Pending',
    entityId: 'pay-02',
    entityType: 'payment',
    amount: 3500,
    studentName: 'Lebohang Matlhoane',
    roomNumber: 'Room 02',
    actor: 'Student (L Matlhoane)',
  },
  {
    id: 'act-6',
    title: 'Maintenance task resolved',
    subtitle: 'Window latch bracket (Room 01) repaired and tested secure by Caretaker Themba. Cost: R120.',
    timeAgo: '2 days ago',
    timestamp: '22 Feb 2026, 16:30',
    type: 'maintenance',
    status: 'Resolved',
    previousStatus: 'In Progress',
    entityId: 'MR-104',
    entityType: 'maintenance',
    studentName: 'Ramadulwane Daniel Mohlomi',
    roomNumber: 'Room 01',
    priority: 'Low',
    actor: 'Caretaker Themba',
  },
  {
    id: 'act-7',
    title: 'Agreement updated & verified',
    subtitle: 'Block A - Room 01 • Lease renewed and countersigned for 2026 academic calendar.',
    timeAgo: '3 days ago',
    timestamp: '21 Feb 2026, 11:00',
    type: 'agreement',
    status: 'Active',
    entityId: 'SA001',
    entityType: 'agreement',
    studentName: 'Ramadulwane Daniel Mohlomi',
    roomNumber: 'Room 01',
    actor: 'Owner (Ms PC Makhele)',
  },
  {
    id: 'act-8',
    title: 'New student registration completed',
    subtitle: 'Ramadulwane Daniel Mohlomi registered and assigned to Room 01 (Block A).',
    timeAgo: '4 days ago',
    timestamp: '20 Feb 2026, 09:15',
    type: 'registration',
    entityType: 'student',
    studentName: 'Ramadulwane Daniel Mohlomi',
    roomNumber: 'Room 01',
    actor: 'Student Resident',
  },
];

export const initialOwnerProfile: OwnerProfile = {
  name: 'Ms PC Makhele',
  title: 'Property Owner',
  email: 'makhelepulane1@gmail.com',
  phone: '+27 82 123 4567',
  alternativePhone: 'Not set',
  bankName: 'Capitec Bank',
  accountNumber: '123456789',
  accountType: 'Cheque',
  paymentReference: 'SA001',
  notifications: {
    newBookings: true,
    rentPayments: true,
    maintenanceAlerts: true,
  },
};

export const monthlyRevenueStats = [
  { month: 'Sep', amount: 5000, label: 'R5k' },
  { month: 'Oct', amount: 6500, label: 'R6.5k' },
  { month: 'Nov', amount: 7000, label: 'R7k' },
  { month: 'Dec', amount: 8000, label: 'R8k' },
  { month: 'Jan', amount: 10000, label: 'R10k' },
];

export const initialMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: 'MR-101',
    studentId: 'stud-1',
    studentName: 'Ramadulwane Daniel Mohlomi',
    studentNumber: '222082927',
    studentPhone: '+27 67 240 2175',
    studentEmail: 'mramadulwane@gmail.com',
    roomId: 'room-01',
    roomNumber: 'Room 01',
    block: 'Block A',
    areaLocation: 'Study Desk Area',
    title: 'Flickering study desk lamp socket & power surge',
    category: 'Electrical',
    priority: 'Medium',
    description: 'The wall power plug socket next to the study desk flickers and causes sparks when plugging in the laptop charger. Needs socket faceplate inspection and wiring check.',
    status: 'Scheduled',
    createdAt: '23 Feb 2026, 14:20',
    updatedAt: '24 Feb 2026, 08:30',
    preferredAccessTime: 'Morning (08:00 - 12:00)',
    assignedTechnician: 'David Ndlovu (Certified Electrician)',
    scheduledDate: '25 Feb 2026, 10:00 AM',
    ownerNotes: 'Technician booked for inspection tomorrow morning. Resident was notified via app.',
    costEstimate: 450,
    photoAttachment: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&auto=format&fit=crop&q=80',
    statusHistory: [
      {
        status: 'Reported',
        timestamp: '23 Feb 2026, 14:20',
        note: 'Issue submitted by student via mobile app',
        updatedBy: 'RD Mohlomi',
      },
      {
        status: 'Scheduled',
        timestamp: '24 Feb 2026, 08:30',
        note: 'Assigned to David Ndlovu for Wednesday 10:00 inspection',
        updatedBy: 'Owner (Ms PC Makhele)',
      },
    ],
  },
  {
    id: 'MR-102',
    studentId: 'stud-2',
    studentName: 'Lebohang Matlhoane',
    studentNumber: '222059872',
    studentPhone: '+27 67 240 8891',
    studentEmail: 'lmatlhoane@gmail.com',
    roomId: 'room-02',
    roomNumber: 'Room 02',
    block: 'Block B',
    areaLocation: 'Ensuite Bathroom',
    title: 'Continuous leaking shower mixer valve & low water pressure',
    category: 'Plumbing',
    priority: 'High',
    description: 'Continuous water drip from the hot water shower mixer valve causing water pooling on bathroom floor and noticeable pressure loss.',
    status: 'In Progress',
    createdAt: '22 Feb 2026, 11:15',
    updatedAt: '24 Feb 2026, 09:10',
    preferredAccessTime: 'Afternoon (12:00 - 17:00)',
    assignedTechnician: 'Sipho Khumalo (FastPlumb Services)',
    scheduledDate: '24 Feb 2026, 14:00 PM',
    ownerNotes: 'Plumber dispatched to premises with replacement ceramic mixer cartridge.',
    costEstimate: 680,
    photoAttachment: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&auto=format&fit=crop&q=80',
    statusHistory: [
      {
        status: 'Reported',
        timestamp: '22 Feb 2026, 11:15',
        note: 'Reported by resident',
        updatedBy: 'L Matlhoane',
      },
      {
        status: 'Scheduled',
        timestamp: '23 Feb 2026, 10:00',
        note: 'Contracted FastPlumb Services for Tuesday',
        updatedBy: 'Owner (Ms PC Makhele)',
      },
      {
        status: 'In Progress',
        timestamp: '24 Feb 2026, 09:10',
        note: 'Plumber arrived on site, currently replacing valve',
        updatedBy: 'Owner (Ms PC Makhele)',
      },
    ],
  },
  {
    id: 'MR-103',
    studentId: 'stud-3',
    studentName: 'Letlotlo P Moloi',
    studentNumber: '222093279',
    studentPhone: '+27 63 465 6632',
    studentEmail: 'yadayadamoloi98@gmail.com',
    roomId: 'room-03',
    roomNumber: 'Room 03',
    block: 'Block A',
    areaLocation: 'Room Entrance Door',
    title: 'Deadbolt lock cylinder sticking and difficult to turn',
    category: 'Keys & Locks',
    priority: 'High',
    description: 'The key gets severely stuck when attempting to lock or unlock the exterior deadbolt. Resident was almost locked outside yesterday evening.',
    status: 'Reported',
    createdAt: '24 Feb 2026, 08:45',
    updatedAt: '24 Feb 2026, 08:45',
    preferredAccessTime: 'Student Must Be Present',
    photoAttachment: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=400&auto=format&fit=crop&q=80',
    statusHistory: [
      {
        status: 'Reported',
        timestamp: '24 Feb 2026, 08:45',
        note: 'Resident submitted emergency lock report',
        updatedBy: 'LP Moloi',
      },
    ],
  },
  {
    id: 'MR-104',
    studentId: 'stud-1',
    studentName: 'Ramadulwane Daniel Mohlomi',
    studentNumber: '222082927',
    studentPhone: '+27 67 240 2175',
    studentEmail: 'mramadulwane@gmail.com',
    roomId: 'room-01',
    roomNumber: 'Room 01',
    block: 'Block A',
    areaLocation: 'Bedroom Window',
    title: 'Loose window latch bracket rattling in wind',
    category: 'Carpentry & Furniture',
    priority: 'Low',
    description: 'Window stay bracket latch was loose and rattling during windy evenings.',
    status: 'Resolved',
    createdAt: '18 Feb 2026, 10:00',
    updatedAt: '20 Feb 2026, 16:30',
    assignedTechnician: 'Caretaker Themba',
    ownerNotes: 'Replaced screws and tightened bracket anchor. Tested secure close.',
    costEstimate: 120,
    statusHistory: [
      {
        status: 'Reported',
        timestamp: '18 Feb 2026, 10:00',
        note: 'Reported by resident',
        updatedBy: 'RD Mohlomi',
      },
      {
        status: 'In Progress',
        timestamp: '19 Feb 2026, 11:00',
        note: 'Caretaker Themba assigned',
        updatedBy: 'Owner',
      },
      {
        status: 'Resolved',
        timestamp: '20 Feb 2026, 16:30',
        note: 'Repaired and verified closed',
        updatedBy: 'Caretaker Themba',
      },
    ],
  },
];
